version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    command: npm run start:dev
    depends_on: 
      - db
    environment: 
      DATABASE_URL: postgres://user:password@postgres:5432/nestjs
      NODE_ENV: development
      PORT: 3000
    ports:
      - 8080:3000
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nestjs
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: